export const sriLankaCities = [
  "Colombo",
  "Dehiwala-Mount Lavinia",
  "Moratuwa",
  "Jaffna",
  "Negombo",
  "Pita Kotte",
  "Sri Jayewardenepura Kotte",
  "Kandy",
  "Trincomalee",
  "Kalmunai",
  "Galle",
  "Point Pedro",
  "Batticaloa",
  "Katunayaka",
  "Valvedditturai",
  "Matara",
  "Battaramulla South",
  "Dambulla",
  "Maharagama",
  "Kotikawatta",
  "Anuradhapura",
  "Vavuniya",
  "Kolonnawa",
  "Hendala",
  "Ratnapura",
  "Badulla",
  "Puttalam",
  "Devinuwara",
  "Welisara",
  "Kalutara",
  "Bentota",
  "Matale",
  "Homagama",
  "Beruwala",
  "Panadura",
  "Mulleriyawa",
  "Kandana",
  "Ja Ela",
  "Wattala",
  "Peliyagoda",
  "Kelaniya",
  "Kurunegala",
  "Nuwara Eliya",
  "Gampola",
  "Chilaw",
  "Eravur Town",
  "Hanwella Ihala",
  "Weligama",
  "Vakarai",
  "Kataragama",
  "Ambalangoda",
  "Ampara",
  "Kegalle",
  "Hatton",
  "Polonnaruwa",
  "Kilinochchi",
  "Tangalle",
  "Monaragala",
  "gampaha"
];
